"""empty message

Revision ID: 0de026e787ea
Revises: c5622d7717a1
Create Date: 2016-10-22 23:51:04.914213

"""

# revision identifiers, used by Alembic.
revision = '0de026e787ea'
down_revision = 'c5622d7717a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_episode_tmdb_id', table_name='episode')
    op.create_index(op.f('ix_episode_tmdb_id'), 'episode', ['tmdb_id'], unique=True)
    op.drop_index('ix_season_tmdb_id', table_name='season')
    op.create_index(op.f('ix_season_tmdb_id'), 'season', ['tmdb_id'], unique=True)
    op.drop_index('ix_show_tmdb_id', table_name='show')
    op.create_index(op.f('ix_show_tmdb_id'), 'show', ['tmdb_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_show_tmdb_id'), table_name='show')
    op.create_index('ix_show_tmdb_id', 'show', ['tmdb_id'], unique=False)
    op.drop_index(op.f('ix_season_tmdb_id'), table_name='season')
    op.create_index('ix_season_tmdb_id', 'season', ['tmdb_id'], unique=False)
    op.drop_index(op.f('ix_episode_tmdb_id'), table_name='episode')
    op.create_index('ix_episode_tmdb_id', 'episode', ['tmdb_id'], unique=False)
    ### end Alembic commands ###
