"""empty message

Revision ID: 1afb5c1c943f
Revises: 6964b6bbcf92
Create Date: 2016-09-06 12:56:28.497714

"""

# revision identifiers, used by Alembic.
revision = '1afb5c1c943f'
down_revision = '6964b6bbcf92'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'genre_service_fkey', 'genre', type_='foreignkey')
    op.drop_column('genre', 'service')
    op.drop_constraint(u'network_service_fkey', 'network', type_='foreignkey')
    op.drop_column('network', 'service')
    op.drop_constraint(u'person_external_id_service_fkey', 'person_external_id', type_='foreignkey')
    op.drop_column('person_external_id', 'url_prefix')
    op.create_unique_constraint(None, 'show_external_id', ['identifier'])
    op.drop_constraint(u'show_external_id_service_fkey', 'show_external_id', type_='foreignkey')
    op.drop_column('show_external_id', 'url_prefix')
    op.drop_table('external_service')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show_external_id', sa.Column('url_prefix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(u'show_external_id_service_fkey', 'show_external_id', 'external_service', ['service'], ['id'])
    op.drop_constraint(None, 'show_external_id', type_='unique')
    op.add_column('person_external_id', sa.Column('url_prefix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(u'person_external_id_service_fkey', 'person_external_id', 'external_service', ['service'], ['id'])
    op.add_column('network', sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'network_service_fkey', 'network', 'external_service', ['service'], ['id'])
    op.add_column('genre', sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'genre_service_fkey', 'genre', 'external_service', ['service'], ['id'])
    op.create_table('external_service',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('base_url', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'external_service_pkey'),
    sa.UniqueConstraint('name', name=u'external_service_name_key')
    )
    ### end Alembic commands ###
