"""empty message

Revision ID: 57643c23c5c2
Revises: d76a40aa0f63
Create Date: 2016-10-22 21:58:22.862614

"""

# revision identifiers, used by Alembic.
revision = '57643c23c5c2'
down_revision = 'd76a40aa0f63'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_people')
    op.drop_table('person_external_id')
    op.drop_table('show_genres')
    op.drop_table('show_external_id')
    op.drop_table('genre')
    op.drop_table('person')
    op.drop_column('show', 'popularity')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('popularity', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_table('person',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('person_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'person_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text(u"nextval('genre_id_seq'::regclass)"), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'genre_pkey'),
    sa.UniqueConstraint('name', name=u'genre_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('show_external_id',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['show_id'], [u'show.id'], name=u'show_external_id_show_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'show_external_id_pkey'),
    sa.UniqueConstraint('identifier', name=u'show_external_id_identifier_key')
    )
    op.create_table('show_genres',
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], [u'genre.id'], name=u'show_genres_genre_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], [u'show.id'], name=u'show_genres_show_id_fkey')
    )
    op.create_table('person_external_id',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('service', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], [u'person.id'], name=u'person_external_id_person_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'person_external_id_pkey'),
    sa.UniqueConstraint('identifier', name=u'person_external_id_identifier_key')
    )
    op.create_table('show_people',
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], [u'person.id'], name=u'show_people_person_id_fkey'),
    sa.ForeignKeyConstraint(['show_id'], [u'show.id'], name=u'show_people_show_id_fkey')
    )
    ### end Alembic commands ###
