"""empty message

Revision ID: 6964b6bbcf92
Revises: 4b20c03b5a67
Create Date: 2016-08-03 16:46:03.410366

"""

# revision identifiers, used by Alembic.
revision = '6964b6bbcf92'
down_revision = '4b20c03b5a67'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('_first_air_date', sa.Date(), nullable=True))
    with op.batch_alter_table('show') as batch_op:
        ### commands auto generated by Alembic - please adjust! ###
        batch_op.drop_column('first_air_date')
    # op.drop_column('show', 'first_air_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('first_air_date', sa.DATE(), nullable=True))
    op.drop_column('show', '_first_air_date')
    ### end Alembic commands ###
