"""empty message

Revision ID: 6e39085a8c76
Revises: None
Create Date: 2016-08-03 12:03:10.929482

"""

# revision identifiers, used by Alembic.
revision = '6e39085a8c76'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('prefix_url', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('homepage', sa.String(length=250), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('poster_path', sa.String(length=100), nullable=True),
    sa.Column('backdrop_path', sa.String(length=100), nullable=True),
    sa.Column('first_air_date', sa.Date(), nullable=True),
    sa.Column('origin_country', sa.String(length=10), nullable=True),
    sa.Column('popularity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_show_name'), 'show', ['name'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['external_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('network',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['external_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('person_external_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['service'], ['external_service.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier')
    )
    op.create_table('season',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.SmallInteger(), nullable=True),
    sa.Column('poster_path', sa.String(length=100), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('episode_count', sa.SmallInteger(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_external_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('identifier', sa.String(length=150), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service'], ['external_service.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('show_people',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], )
    )
    op.create_table('show_genres',
    sa.Column('genre_id', sa.Integer(), nullable=True),
    sa.Column('show_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.ForeignKeyConstraint(['show_id'], ['show.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('show_genres')
    op.drop_table('show_people')
    op.drop_table('show_external_id')
    op.drop_table('season')
    op.drop_table('person_external_id')
    op.drop_table('network')
    op.drop_table('genre')
    op.drop_index(op.f('ix_show_name'), table_name='show')
    op.drop_table('show')
    op.drop_table('person')
    op.drop_table('external_service')
    ### end Alembic commands ###
