"""empty message

Revision ID: afbb266bca6b
Revises: 57643c23c5c2
Create Date: 2016-10-22 22:10:40.037789

"""

# revision identifiers, used by Alembic.
revision = 'afbb266bca6b'
down_revision = '57643c23c5c2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('episode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('episode_number', sa.SmallInteger(), nullable=True),
    sa.Column('still_path', sa.String(length=100), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episode_name'), 'episode', ['name'], unique=False)
    op.add_column(u'season', sa.Column('name', sa.String(length=250), nullable=True))
    op.add_column(u'season', sa.Column('overview', sa.Text(), nullable=True))
    op.create_index(op.f('ix_season_name'), 'season', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_season_name'), table_name='season')
    op.drop_column(u'season', 'overview')
    op.drop_column(u'season', 'name')
    op.drop_index(op.f('ix_episode_name'), table_name='episode')
    op.drop_table('episode')
    ### end Alembic commands ###
