"""empty message

Revision ID: c5622d7717a1
Revises: afbb266bca6b
Create Date: 2016-10-22 23:23:00.529562

"""

# revision identifiers, used by Alembic.
revision = 'c5622d7717a1'
down_revision = 'afbb266bca6b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('episode', sa.Column('tmdb_data', postgresql.JSONB(), nullable=True))
    op.add_column('episode', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_episode_tmdb_id'), 'episode', ['tmdb_id'], unique=False)
    op.drop_column('episode', 'still_path')
    op.drop_column('episode', 'air_date')
    op.add_column('season', sa.Column('season_number', sa.SmallInteger(), nullable=True))
    op.add_column('season', sa.Column('tmdb_data', postgresql.JSONB(), nullable=True))
    op.add_column('season', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_season_tmdb_id'), 'season', ['tmdb_id'], unique=False)
    op.drop_column('season', 'poster_path')
    op.drop_column('season', 'number')
    op.drop_column('season', 'episode_count')
    op.drop_column('season', 'air_date')
    op.add_column('show', sa.Column('tmdb_data', postgresql.JSONB(), nullable=True))
    op.add_column('show', sa.Column('tmdb_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_show_tmdb_id'), 'show', ['tmdb_id'], unique=False)
    op.drop_column('show', 'status')
    op.drop_column('show', 'origin_country')
    op.drop_column('show', 'poster_path')
    op.drop_column('show', '_first_air_date')
    op.drop_column('show', 'homepage')
    op.drop_column('show', 'backdrop_path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('backdrop_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('homepage', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('_first_air_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('poster_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('origin_country', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('show', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_show_tmdb_id'), table_name='show')
    op.drop_column('show', 'tmdb_id')
    op.drop_column('show', 'tmdb_data')
    op.add_column('season', sa.Column('air_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('season', sa.Column('episode_count', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('season', sa.Column('number', sa.SMALLINT(), autoincrement=False, nullable=True))
    op.add_column('season', sa.Column('poster_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_season_tmdb_id'), table_name='season')
    op.drop_column('season', 'tmdb_id')
    op.drop_column('season', 'tmdb_data')
    op.drop_column('season', 'season_number')
    op.add_column('episode', sa.Column('air_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('episode', sa.Column('still_path', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_episode_tmdb_id'), table_name='episode')
    op.drop_column('episode', 'tmdb_id')
    op.drop_column('episode', 'tmdb_data')
    ### end Alembic commands ###
