"""empty message

Revision ID: d76a40aa0f63
Revises: 1afb5c1c943f
Create Date: 2016-09-06 13:02:23.076371

"""

# revision identifiers, used by Alembic.
revision = 'd76a40aa0f63'
down_revision = '1afb5c1c943f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('network')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('identifier', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'network_pkey'),
    sa.UniqueConstraint('name', name=u'network_name_key')
    )
    ### end Alembic commands ###
